const err = [
  { abbrechen: "iptal etmek, kesmek" },
  { abhängen: "bağlı olmak, takılmak" },
  { ablaufen: "süresi dolmak" },
  { abnehmen: "kilo vermek, azalmak" },
  { abschließen: "kilitlemek, tamamlamak" },
  { abschneiden: "kesmek" },
  { abschreiben: "kopya çekmek, bir yerden yazmak" },
  { absenden: "göndermek" },
  { absinken: "batmak, alçalmak" },
  { absteigen: "inmek (bisiklet, at vb.)" },
  { angeben: "belirtmek" },
  { angreifen: "saldırmak" },
  { anhalten: "durdurmak" },
  { anlügen: "yalan söylemek" },
  { annehmen: "kabul etmek" },
  { ansehen: "bakmak" },
  { ansprechen: "hitap etmek" },
  { ansteigen: "artmak, yükselmek" },
  { anwachsen: "büyümek, artmak" },
  { anwenden: "uygulamak" },
  { anziehen: "giyinmek, çekmek" },
  { aufbrechen: "kırmak, yola çıkmak" },
  { aufessen: "yiyip bitirmek" },
  { aufgeben: "pes etmek" },
  { aufhalten: "durdurmak" },
  { aufheben: "kaldırmak" },
  { aufnehmen: "kabul etmek, kaydetmek" },
  { aufstehen: "ayağa kalkmak" },
  { auftreten: "sahneye çıkmak" },
  { aufwachsen: "büyümek (çocuk)" },
  { ausbrechen: "patlak vermek, kaçmak" },
  { ausfallen: "iptal olmak, dökülmek (saç)" },
  { ausgehen: "dışarı çıkmak" },
  { aushalten: "dayanmak" },
  { ausleihen: "ödünç vermek" },
  { aussehen: "görünmek" },
  { aussteigen: "inmek (taşıttan)" },
  { ausziehen: "soyunmak, taşınmak (evden)" },
  { backen: "fırında pişirmek" },
  { begreifen: "anlamak" },
  { behalten: "saklamak, korumak" },
  { beibringen: "öğretmek" },
  { beiseitelegen: "bir kenara koymak" },
  { beitragen: "katkıda bulunmak" },
  { bekommen: "almak" },
  { beraten: "danışmak, tavsiye vermek" },
  { beschließen: "karar vermek" },
  { beschreiben: "tanımlamak" },
  { besprechen: "görüşmek" },
  { bestehen: "başarmak, var olmak" },
  { betragen: "tutmak, etmek (miktar)" },
  { betreiben: "işletmek" },
  { betrügen: "aldatmak" },
  { beweisen: "kanıtlamak" },
  { bewerben: "başvurmak (iş vb.)" },
  { bieten: "teklif etmek" },
  { binden: "bağlamak" },
  { bitten: "rica etmek" },
  { bleiben: "kalmak" },
  { brechen: "kırmak" },
  { brennen: "yanmak" },
  { bringen: "getirmek" },
  { denken: "düşünmek" },
  { dreschen: "dövmek" },
  { dringen: "nüfuz etmek" },
  { dürfen: "izinli olmak" },
  { einbrechen: "hırsızlık yapmak, zorla girmek" },
  { einfallen: "aklına gelmek" },
  { eingeben: "girmek (bilgi)" },
  { eingehen: "girmek" },
  { einhalten: "uymak" },
  { einladen: "davet etmek" },
  { einnehmen: "almak (ilaç vb.)" },
  { einschlafen: "uykuya dalmak" },
  { einschließen: "kilitlemek, içermek" },
  { einsehen: "anlamak, görmek" },
  { einsteigen: "binmek (taşıta)" },
  { eintragen: "kaydetmek, yazmak" },
  { einwerfen: "atmak" },
  { einziehen: "taşınmak (yeni eve)" },
  { empfehlen: "tavsiye etmek" },
  { empfangen: "almak (misafir vb.)" },
  { empfinden: "hissetmek" },
  { enthalten: "içermek" },
  { entlassen: "işten çıkarmak" },
  { entscheiden: "karar vermek" },
  { entschließen: "karar vermek" },
  { entsprechen: "karşılamak" },
  { entstehen: "meydana gelmek" },
  { erfinden: "icat etmek" },
  { erhalten: "almak" },
  { erkennen: "tanımak" },
  { erschaffen: "yaratmak" },
  { erschließen: "erişmek" },
  { erschrecken: "korkmak, korkutmak" },
  { ersinnen: "tasarlamak" },
  { erziehen: "yetiştirmek" },
  { essen: "yemek yemek" },
  { fahren: "sürmek, gitmek (araçla)" },
  { fallen: "düşmek" },
  { fangen: "yakalamak" },
  { finden: "bulmak" },
  { fliegen: "uçmak" },
  { fliehen: "kaçmak" },
  { fließen: "akmak" },
  { fressen: "yemek (hayvan için)" },
  { frieren: "donmak, üşümek" },
  { geben: "vermek" },
  { gehen: "gitmek" },
  { gelingen: "başarmak" },
  { genießen: "tadını çıkarmak" },
  { geschehen: "olmak, meydana gelmek" },
  { gewinnen: "kazanmak" },
  { gießen: "dökmek, sulamak" },
  { gleichen: "benzemek" },
  { gleiten: "kaymak" },
  { graben: "kazmak" },
  { greifen: "yakalamak, tutmak" },
  { haben: "sahip olmak" },
  { halten: "tutmak" },
  { hängen: "asmak, asılı durmak" },
  { heben: "kaldırmak" },
  { heißen: "adı olmak" },
  { helfen: "yardım etmek" },
  { herstellen: "üretmek" },
  { hinweisen: "işaret etmek" },
  { kennen: "tanımak" },
  { klingen: "çalmak (ses)" },
  { kommen: "gelmek" },
  { können: "yapabilmek" },
  { kriechen: "sürünmek" },
  { laden: "yüklemek, çağırmak" },
  { lassen: "bırakmak, izin vermek" },
  { laufen: "koşmak" },
  { leiden: "acı çekmek" },
  { leihen: "ödünç almak" },
  { lesen: "okumak" },
  { liegen: "yatmak, bulunmak" },
  { lügen: "yalan söylemek" },
  { messen: "ölçmek" },
  { mögen: "sevmek, hoşlanmak" },
  { müssen: "zorunda olmak" },
  { nehmen: "almak" },
  { nennen: "adlandırmak" },
  { pfeifen: "ıslık çalmak" },
  { raten: "tavsiye vermek, tahmin etmek" },
  { reiten: "ata binmek" },
  { riechen: "koklamak, kokmak" },
  { rufen: "çağırmak" },
  { schaffen: "yaratmak, başarmak" },
  { scheinen: "parlamak, görünmek" },
  { schieben: "itmek" },
  { schießen: "ateş etmek" },
  { schlafen: "uyumak" },
  { schlagen: "vurmak" },
  { schleichen: "sessizce yaklaşmak" },
  { schließen: "kapatmak" },
  { schlingen: "sarmak, yutmak" },
  { schmeißen: "fırlatmak" },
  { schmelzen: "erimek, eritmek" },
  { schneiden: "kesmek" },
  { schreiben: "yazmak" },
  { schreien: "bağırmak" },
  { schweigen: "susmak" },
  { schwimmen: "yüzmek" },
  { sehen: "görmek" },
  { sein: "olmak" },
  { singen: "şarkı söylemek" },
  { sinken: "batmak, düşmek" },
  { sitzen: "oturmak" },
  { sprechen: "konuşmak" },
  { springen: "zıplamak" },
  { stechen: "sokmak, batırmak" },
  { stehen: "durmak" },
  { stehlen: "çalmak" },
  { steigen: "tırmanmak, yükselmek" },
  { sterben: "ölmek" },
  { stoßen: "itmek" },
  { streichen: "boyamak, iptal etmek" },
  { streiten: "tartışmak" },
  { tragen: "taşımak" },
  { treffen: "buluşmak" },
  { treiben: "sürmek (spor vb.)" },
  { trinken: "içmek" },
  { tun: "yapmak" },
  { vergessen: "unutmak" },
  { verstehen: "anlamak" },
  { verlieren: "kaybetmek" },
  { verlassen: "terk etmek" },
  { verschwinden: "kaybolmak" },
  { verzeihen: "affetmek" },
  { wachsen: "büyümek, gelişmek" },
  { wählen: "seçmek" },
  { waschen: "yıkamak" },
  { wecken: "uyandırmak" },
  { werden: "olmak" },
  { werfen: "fırlatmak" },
  { wissen: "bilmek" },
  { wollen: "istemek" },
  { ziehen: "çekmek" },
  { zwingen: "zorlamak" },
  { abbaubar: "biyolojik olarak parçalanabilir" },
  { abbauen: "sökmek, azaltmak, yıkmak" },
  { abbilden: "göstermek, resmetmek" },
  { abbrechen: "kırmak, iptal etmek" },
  { Abgaswert: "egzoz emisyon değeri" },
  { abgeben: "vermek, teslim etmek" },
  { abhandenkommen: "kaybolmak" },
  { Abholzung: "ormanın kesilmesi, tahribat" },
  { ablegen: "çıkarmak, bırakmak" },
  { ablenken: "dikkat dağıtmak" },
  { ablesen: "okumak, okumak (sayacı vb.)" },
  { abnehmen: "azaltmak, zayıflamak" },
  { abnutzen: "aşındırmak, kullanarak eskimek" },
  { Abrechnung: "hesap, hesaplaşma" },
  { absaugen: "emmek, çekmek" },
  { abschaffen: "ortadan kaldırmak" },
  { Abschiebung: "geri gönderme, sınır dışı etme" },
  { Absolvent: "mezun" },
  { absolvieren: "tamamlamak, bitirmek" },
  { abstammen: "soyundan gelmek" },
  { Abstand: "mesafe, uzaklık" },
  { abstauben: "toz almak" },
  { abstreiten: "inkar etmek" },
  { abstürzen: "düşmek, çakılmak" },
  { abweichen: "sapmak, farklı olmak" },
  { abwenden: "yön değiştirmek, çevirmek" },
  { abwinken: "elle işaret etmek, el sallamak" },
  { abwischen: "silmek, süpürmek" },
  { Adel: "soyluluk" },
  { Adlige: "soylu, aristokrat" },
  { Akkordeon: "akordeon (müzik aleti)" },
  { akut: "acil, şiddetli" },
  { akzentfrei: "aksansız" },
  { Alltagssprache: "günlük dil" },
  { altern: "yaşlanmak" },
  { Alterspyramide: "yaş piramidi" },
  { Altersstruktur: "yaş yapısı" },
  { altmodisch: "eski moda" },
  { Aluminium: "alüminyum" },
  { Anfall: "kriz, atak" },
  { anfallen: "saldırmak, ortaya çıkmak" },
  { anfühlen: "hissetmek, dokunmak" },
  { Angehörige: "yakın, aile üyeleri" },
  { Angeklagte: "sanık" },
  { Angelegenheit: "mesele, konu" },
  { angemessen: "uygun, yerinde" },
  { Anhang: "ek, ilave" },
  { anklagen: "suçlamak" },
  { Ankläger: "savcı" },
  { anlegen: "yatırım yapmak, yerleştirmek" },
  { anpassen: "uydurmak, adapte olmak" },
  { Anpassung: "adaptasyon" },
  { Anschreiben: "yazı, başvuru" },
  { Ansehen: "saygınlık, itibar" },
  { Anspielung: "belirti, ima" },
  { Anspitzer: "kalem traş" },
  { ansprechbar: "konuşulabilir" },
  { ansprechen: "konuşmak, hitap etmek" },
  { anspruchsvoll: "iddialı, zorlayıcı" },
  { ansteckend: "bulaşıcı" },
  { ansteigen: "yükselmek, artmak" },
  { Anteil: "pay, hisse" },
  { Antibiotikum: "antibiyotik" },
  { antik: "antik, eski" },
  { Antike: "antik çağ" },
  { Antisemitismus: "antisemitizm" },
  { Antragsteller: "başvuru sahibi" },
  { Anwendung: "uygulama" },
  { anwerben: "işe almak" },
  { Anziehungskraft: "çekim gücü" },
  { Arbeitskraft: "iş gücü" },
  { archäologisch: "arkeolojik" },
  { Architektur: "mimari" },
  { Ärger: "öfke, sıkıntı" },
  { Armut: "yoksulluk" },
  { Artensterben: "türlerin yok olması" },
  { Artenvielfalt: "biyoçeşitlilik" },
  { Arzneimittel: "ilaç" },
  { Aschenbecher: "kül tablası" },
  { Atmosphäre: "atmosfer" },
  { Atmung: "nefes alma" },
  { Atom: "atom" },
  { Atomkern: "atom çekirdeği" },
  { aufbauen: "kurmak, inşa etmek" },
  { aufbewahren: "saklamak" },
  { aufbrauchen: "tüketmek" },
  { aufbrechen: "yola çıkmak" },
  { Auffassung: "görüş, düşünce" },
  { Aufklärung: "aydınlanma" },
  { aufkommen: "ortaya çıkmak" },
  { aufladen: "şarj etmek" },
  { aufmuntern: "neşelendirmek" },
  { aufnehmen: "almak, kaydetmek" },
  { aufsetzen: "kurmak, yerleştirmek" },
  { aufstellen: "kurmak, dikmek" },
  { aufstoßen: "itmek, kalkmak" },
  { auftreiben: "bulmak" },
  { aufwachsen: "büyümek" },
  { aufweisen: "göstermek, sergilemek" },
  { Ausbau: "genişletme" },
  { Ausbeutung: "sömürü" },
  { ausbleiben: "olmamak, gelmemek" },
  { ausbrechen: "kaçmak, patlak vermek" },
  { ausbreiten: "yayılmak" },
  { Ausbreitung: "yayılma" },
  { ausdrücken: "ifade etmek" },
  { auseinandergehen: "ayrılmak, dağılmak" },
  { Koscher: "Yahudi dini kurallarına uygun, helal" },
  { Sich_genieren: "Utanmak, sıkılmak" },
  { Sich_trauen: "Cesaret etmek" },
  { Wurscht: "Önemsiz" },
  { Entlassen: "İşten çıkarmak, dahil olmamak" },
  { Leichte_Beute: "Kolay av" },
  { Alkuma: "Şeytan, iblis" },
  { Wegnehmen: "Elinden almak" },
  { Wetterfee: "Hava perisi" },
  { Schlendern: "Yavaşça yürümek" },
  { Pech: "Şanssızlık" },
  { Abmachen: "Anlaşmak, kararlaştırmak" },
  { Erfüllen: "Bir isteği yerine getirmek" },
  { Aufzeigen: "Göstermek, ortaya koymak" },
  { Sich_hingeben: "Kendini adamak, kaptırmak" },
  { Worum_gehts: "Konu ne, mesele ne?" },
  { Sensationell_gut: "Aşırı derecede iyi" },
  { Übernehmen: "Devralmak" },
  { Ausfragen: "Sorguya çekmek" },
  { Vorsichtig_sein: "Dikkatli olmak" },
  { Ist_das_so: "Öyle mi?" },
  { Furchtbar: "Korkunç, berbat" },
  { Aufgeben: "Vazgeçmek, bırakmak" },
  { Auslösen: "Tetiklemek" },
  { Im_Grunde: "Aslında, temelde" },
  { Nachweislich: "Kesin kanıtlı" },
  { Ranghoh: "Rütbesi yüksek, önemli biri" },
  { Auf_keinen_Fall: "Asla" },
  { Der_Trainer: "Antrenör" },
  { Sich_aufführen: "Abartılı davranmak" },
  { Entstandener_Schaden: "Meydana gelen zarar" },
  { Vollumfänglich: "Tam kapsamlı" },
  { Kooperieren: "İş birliği yapmak" },
  { Pleite: "İflas" },
  { Erfolgen: "Meydana gelmek, gerçekleşmek" },
  { Bangen: "Endişelenmek" },
  { Fassungslos: "Şaşkın, afallamış" },
  { Schlottern: "Aşırı titremek" },
  { Horrisch: "Başlıca, otoriter" },
  {
    verrückt_sein_nach_etwas:
      "Bir şeye delice tutkun olmak, Bir şeyi her zaman yapmak istiyor olmak.",
  },
  {
    Die_Augen_auf_etwas_richten: "Gözlerini bir şeye dikmek, Bir şeyi izlemek.",
  },
  {
    nicht_von_schlechten_Eltern_sein:
      "Kötü anne babadan olmamak, Oldukça iyi olmak.",
  },
  { Kopf_hoch: "Kafanı dik!, Üzgün olmamak." },
  { Dabei_sein_ist_alles: "Orada olmak her şey, Zaferin önemli olmadığı." },
  { im_Fjord_Heringe: "Fiyordda ringa balıkları" },
  { hergefischt: "Aşırı avlanmış" },
  { die_Bucht: "Koy" },
  { züchten: "Yetiştirmek" },
  { verändert: "Değişti" },
  { hinterm_Mord: "Cinayetin arkasında" },
  { Na_los: "Hadi bakalım" },
  { austasten: "Yoklamak" },
  { dort: "Orada" },
  { drüben: "Karşıda" },
  { Sitte_die_Tradition: "Gelenek, adet" },
  { Beerdigung: "Cenaze" },
  { er_führt: "O yönetiyor / O yönlendiriyor" },
  { hinterlassen: "Geride bırakmak" },
  { unfair: "Adaletsiz" },
  { mutig: "Cesur" },
  { abgehauen: "Kaçtı" },
  { holt: "Alıyor / Getiriyor" },
  { düster: "Kasvetli" },
  { ausrasten: "Çıldırmak" },
  { abhauen: "Kaçmak" },
  { einkaufen: "Alışveriş yapmak" },
  { zu_geeigneterem_Maße: "Daha uygun ölçüde" },
  { einfach_so: "Öylece mi" },
  { inzwischen: "Bu arada" },
  { abbaubar: "Doğada çözünebilir" },
  { abbauen: "Sökmek, azaltmak" },
  { abbilden: "Resmetmek, temsil etmek" },
  { abbrechen: "Yarıda kesmek" },
  { Abgaswert: "Egzoz değeri" },
  { abgeben: "Teslim etmek" },
  { abhandenkommen: "Kaybolmak" },
  { Abholzung: "Ormansızlaşma" },
  { ablegen: "Bir kenara koymak" },
  { ablenken: "Dikkat dağıtmak" },
  { ablesen: "Okumak (ölçü aletinden)" },
  { abnehmen: "Kilo vermek, azalmak" },
  { abnutzen: "Aşınmak" },
  { Abrechnung: "Hesap kesimi" },
  { absaugen: "Emerek temizlemek" },
  { abschaffen: "Kaldırmak" },
  { Abschiebung: "Sınır dışı etme" },
  { Absolvent: "Mezun" },
  { absolvieren: "Tamamlamak (eğitim)" },
  { abstammen: "Köken almak" },
  { Abstand: "Mesafe" },
  { abstauben: "Tozunu almak" },
  { abstreiten: "İnkâr etmek" },
  { abstürzen: "Çökmek (bilgisayar)" },
  { abweichen: "Sapmak" },
  { abwenden: "Önlemek" },
  { abwinken: "Reddetmek (el hareketiyle)" },
  { abwischen: "Silmek" },
  { Adel: "Soylu sınıfı" },
  { Adlige: "Asilzade" },
  { Akkordeon: "Akordeon" },
  { akut: "Acil" },
  { akzentfrei: "Aksansız" },
  { Alltagssprache: "Günlük dil" },
  { altern: "Yaşlanmak" },
  { Alterspyramide: "Yaş piramidi" },
  { Altersstruktur: "Yaş yapısı" },
  { altmodisch: "Modası geçmiş" },
  { Aluminium: "Alüminyum" },
  { Anfall: "Nöbet (tıp)" },
  { anfallen: "Ortaya çıkmak (atık vb.)" },
  { anfühlen: "Hissetmek" },
  { Angehörige: "Yakın, akraba" },
  { Angeklagte: "Sanık" },
  { Angelegenheit: "Mesele" },
  { angemessen: "Uygun" },
  { Anhang: "Ek (belge)" },
  { anklagen: "Suçlamak" },
  { Ankläger: "Savcı" },
  { anlegen: "Yatırım yapmak" },
  { anpassen: "Uyum sağlamak" },
  { Anpassung: "Uyum" },
  { Anschreiben: "Başvuru mektubu" },
  { Ansehen: "İtibar" },
  { Anspielung: "İma" },
  { Anspitzer: "Kalemtıraş" },
  { ansprechbar: "İletişim kurabilir" },
  { ansprechen: "Hitap etmek" },
  { anspruchsvoll: "Zorlu, talepkar" },
  { ansteckend: "Bulaşıcı" },
  { ansteigen: "Artmak" },
  { Anteil: "Pay" },
  { Antibiotikum: "Antibiyotik" },
  { antik: "Antik" },
  { Antike: "Antik çağ" },
  { Antisemitismus: "Yahudi düşmanlığı" },
  { Antragsteller: "Başvuru sahibi" },
  { Anwendung: "Uygulama" },
  { anwerben: "İşe almak" },
  { Anziehungskraft: "Cazibe" },
  { Arbeitskraft: "İş gücü" },
  { archäologisch: "Arkeolojik" },
  { Architektur: "Mimari" },
  { Ärger: "Öfke" },
  { Armut: "Yoksulluk" },
  { Artensterben: "Türlerin yok oluşu" },
  { Artenvielfalt: "Biyoçeşitlilik" },
  { Arzneimittel: "İlaç" },
  { Aschenbecher: "Kül tablası" },
  { Atmosphäre: "Atmosfer" },
  { Atmung: "Solunum" },
  { Atom: "Atom" },
  { Atomkern: "Atom çekirdeği" },
  { aufbauen: "İnşa etmek" },
  { aufbewahren: "Saklamak" },
  { aufbrauchen: "Tüketmek" },
  { aufbrechen: "Kırmak (kapı vb.)" },
  { Auffassung: "Anlayış" },
  { Aufklärung: "Aydınlanma" },
  { aufkommen: "Ortaya çıkmak" },
  { aufladen: "Şarj etmek" },
  { aufmuntern: "Neşelendirmek" },
  { aufnehmen: "Kaydetmek" },
  { aufsetzen: "Takmak (gözlük vb.)" },
  { aufstellen: "Kurmak" },
  { aufstoßen: "Geğirmek" },
  { auftreiben: "Bulup getirmek" },
  { aufwachsen: "Büyümek" },
  { aufweisen: "Göstermek (özellik)" },
  { Ausbau: "Genişletme" },
  { Ausbeutung: "Sömürü" },
  { ausbleiben: "Gerçekleşmemek" },
  { ausbrechen: "Kaçmak (hapishane)" },
  { ausbreiten: "Yayılmak" },
  { Ausbreitung: "Yayılma" },
  { ausdrücken: "İfade etmek" },
  { auseinandergehen: "Ayrılmak" },
  { ausfallen: "İptal olmak" },
  { ausführlich: "Ayrıntılı" },
  { ausgehen: "Tükenmek" },
  { ausgrenzen: "Dışlamak" },
  { Aushang: "İlan" },
  { auskommen: "Geçinmek" },
  { Ausnahmefall: "İstisnai durum" },
  { ausnutzen: "Sömürmek" },
  { ausprägen: "Belirginleştirmek" },
  { ausreden: "Bahane bulmak" },
  { aussagen: "İfade vermek" },
  { ausscheiden: "Çekilmek" },
  { Ausschlag: "Döküntü (cilt)" },
  { ausschließen: "Hariç tutmak" },
  { ausschreiben: "İlan etmek" },
  { aussortieren: "Ayıklamak" },
  { Ausstattung: "Donanım" },
  { Ausstoß: "Emisyon" },
  { ausstoßen: "Salmak (gaz)" },
  { austauschen: "Değiştirmek" },
  { austreten: "Çıkmak (üyelikten)" },
  { Auswanderer: "Göçmen" },
  { ausweichen: "Kaçınmak" },
  { ausweichend: "Kaçamaklı" },
  { auswerfen: "Fırlatmak" },
  { auswerten: "Değerlendirmek" },
  { auswirken: "Etkilemek" },
  { Auswirkung: "Sonuç" },
  { auszeichnen: "Ödüllendirmek" },
  { Bakterium_Subst: "Bakteri" },
  { Ballett_Subst: "Bale" },
  { barrierefrei_Adj: "Engelsiz" },
  { basieren_Verb: "Dayanmak" },
  { Basis_Subst: "Temel" },
  { Baumwolle_Subst: "Pamuk" },
  { Bauteil_Subst: "Parça (teknik)" },
  { Bedauern_Subst: "Üzüntü" },
  { beeindrucken_Verb: "Etkilemek" },
  { beerdigen_Verb: "Gömmek" },
  { befassen_Refl_Verb: "İlgilenmek" },
  { Befehl_Subst: "Emir" },
  { befestigen_Verb: "Sabitlemek" },
  { Befragung_Subst: "Anket" },
  { befreundet_Adj: "Arkadaş" },
  { begabt_Adj: "Yetenekli" },
  { begehen_Verb: "İşlemek (suç)" },
  { begleichen_Verb: "Ödemek (borç)" },
  { Begriff_Subst: "Kavram" },
  { begründet_Adj: "Gerekçeli" },
  { Behauptung_Subst: "İddia" },
  { Behinderung_Subst: "Engellilik" },
  { beibehalten_Verb: "Sürdürmek" },
  { Bekanntenkreis_Subst: "Tanıdık çevresi" },
  { Bekanntgabe_Subst: "Duyuru" },
  { beklagen_Verb: "Şikâyet etmek" },
  { belegen_Verb: "Kanıtlamak" },
  { bemühen_Verb: "Çaba göstermek" },
  { benachteiligen_Verb: "Dezavantajlı" },
  { bereithalten_Verb: "Hazır bulundurmak" },
  { berücksichtigen_Verb: "Dikkate almak" },
  { beschuldigen_Verb: "Suçlamak" },
  { Besitz_Subst: "Mülkiyet" },
  { Besteck_Subst: "Çatal-bıçak takımı" },
  { bestehen_Verb: "Var olmak" },
  { bestehend_Adj: "Mevcut" },
  { betragen_Verb: "Tutmak (miktar)" },
  { betreffen_Verb: "İlgilendirmek" },
  { Betrieb_Subst: "İşletme" },
  { Betriebswirtschaft_Subst: "İşletme" },
  { bewältigen_Verb: "Üstesinden gelmek" },
  { Bewegung_Subst: "Hareket" },
  { bewilligen_Verb: "Onaylamak" },
  { bewusstlos_Adj: "Bilinçsiz" },
  { bezeichnen_Verb: "Adlandırmak" },
  { Bezeichnung_Subst: "Tanım" },
  { bilden_Verb: "Oluşturmak" },
  { Bildhauerei_Subst: "Heykeltıraşlık" },
  { Bildung_Subst: "Eğitim" },
  { Bindung_Subst: "Bağ" },
  { Bischof_Subst: "Piskopos" },
  { Blase_Subst: "Kabarcık" },
  { Blickkontakt_Subst: "Göz teması" },
  { Blumentopf_Subst: "Saksı" },
  { Blutdruck_Subst: "Tansiyon" },
  { Blütezeit_Subst: "Altın çağ" },
  { Blutprobe_Subst: "Kan testi" },
  { Blutwerte_Subst: "Kan değerleri" },
  { Blutzucker_Subst: "Kan şekeri" },
  { Bodenbelag_Subst: "Zemin kaplaması" },
  { Brauch_Subst: "Gelenek" },
  { Bronze_Subst: "Bronz" },
  { Brüderlichkeit_Subst: "Kardeşlik" },
  { Buchhalter_Subst: "Muhasebeci" },
  { Bürgerkrieg_Subst: "İç savaş" },
  { Büroartikel_Subst: "Ofis malzemesi" },
  { Charmant_Adj: "Zarif, çekici" },
  { Chirurg_Subst: "Cerrah" },
  { Christentum_Subst: "Hristiyanlık" },
  { Christianisieren_Verb: "Hristiyanlaştırmak" },
  { Christlich_Adj: "Hristiyan" },
  { Chronisch_Adj: "Kronik" },
  { Chronologie_Subst: "Zaman dizini" },
  { Chronologisch_Adj: "Kronolojik" },
  { Dackel_Subst: "Dachshund (köpek cinsi)" },
  { Dahinterkommen_Verb: "Anlamak, farkına varmak" },
  { Darm_Subst: "Bağırsak" },
  { Darstellen_ReflVerb: "Temsil etmek" },
  { Daumen_Subst: "Başparmak" },
  { Definieren_Verb: "Tanımlamak" },
  { Demonstrieren_Verb: "Gösteri yapmak" },
  { Denkweise_Subst: "Düşünce tarzı" },
  { Design_Subst: "Tasarım" },
  { Desinfektionsmittel_Subst: "Dezenfektan" },
  { Desinfizieren_Verb: "Dezenfekte etmek" },
  { Detailliert_Adj: "Detaylı" },
  { Detailreich_Adj: "Ayrıntılı" },
  { Deutschstämmig_Adj: "Alman kökenli" },
  { Diktatur_Subst: "Diktatörlük" },
  { Diskriminierung_Subst: "Ayrımcılık" },
  { Display_Subst: "Ekran" },
  { Drama_Subst: "Dram" },
  { Dreitagebart_Subst: "Üç günlük sakal" },
  { Drohnen_Subst: "İnsansız hava aracı" },
  { Durchbrechen_Verb: "Kırmak (engeli)" },
  { Durchbringen_Verb: "Geçindirmek" },
  { Durchfall_Subst: "İshal" },
  { Durchführen_Verb: "Uygulamak" },
  { Durchgehen_Verb: "Gözden geçirmek" },
  { Durchhalten_Verb: "Dayanmak" },
  { Durchlaufen_Verb: "Geçmek (süreç)" },
  { Durchstehen_Verb: "Katlanmak" },
  { Durchziehen_Verb: "Uygulamak (plan)" },
  { Dürre_Subst: "Kuraklık" },
  { E_Bass_Subst: "Bas gitar" },
  { EDV_gestützt_Adj: "Bilgisayar destekli" },
  { Effizient_Adj: "Verimli" },
  { Eierbecher_Subst: "Yumurta kabı" },
  { Eifersucht_Subst: "Kıskançlık" },
  { Eigenschaft_Subst: "Özellik" },
  { Eigentum_Subst: "Mülkiyet" },
  { Einbeziehen_Verb: "Dahil etmek" },
  { Eingangsbestätigung_Subst: "Alındı onayı" },
  { Eingehen_Verb: "Kabul etmek (teklif)" },
  { Eingestehen_Verb: "İtiraf etmek" },
  { Einhalten_Verb: "Uymak (kural)" },
  { Einheimische_Subst: "Yerli" },
  { Einleben_ReflVerb: "Alışmak" },
  { Einleuchten_Verb: "Mantıklı gelmek" },
  { Einmischen_Verb: "Karışmak" },
  { Einreichen_Verb: "Sunmak (belge)" },
  { Einschränken_Verb: "Kısıtlamak" },
  { Einschreiben_ReflVerb: "Kaydolmak" },
  { Einstichstelle_Subst: "İğne izi" },
  { Eintreten_Verb: "Gerçekleşmek" },
  { Einwanderer_Subst: "Göçmen" },
  { Einwandern_Verb: "Göç etmek" },
  { Einwanderungsland_Subst: "Göçmen ülkesi" },
  { Einwegplastik_Subst: "Tek kullanımlık plastik" },
  { Einzigartig_Adj: "Eşsiz" },
  { Eisen_Subst: "Demir" },
  { Ekel_Subst: "Tiksinti" },
  { Eklig_Adj: "İğrenç" },
  { Elektriker_Subst: "Elektrikçi" },
  { Elektrizität_Subst: "Elektrik" },
  { Elektrofahrzeug_Subst: "Elektrikli araç" },
  { Elektromobilität_Subst: "Elektrikli mobilite" },
  { Elektrotechnik_Subst: "Elektrik mühendisliği" },
  { Element_Subst: "Element" },
  { Emission_Subst: "Emisyon" },
  { Emotion_Subst: "Duygu" },
  { Emotional_Adj: "Duygusal" },
  { Energieerzeugung_Subst: "Enerji üretimi" },
  { Entdeckung_Subst: "Keşif" },
  { Entführung_Subst: "Kaçırma" },
  { Entgegenkommen_Verb: "Karşılamak (beklenti)" },
  { Entgiften_Verb: "Detoks yapmak" },
  { Entladen_ReflVerb: "Boşalmak (pil)" },
  { Entnehmen_Verb: "Almak (örnek)" },
  { Entschädigung_Subst: "Tazminat" },
  { Entsetzlich_Adj: "Korkunç" },
  { Entsprechen_Verb: "Karşılık gelmek" },
  { Entwerfen_Verb: "Tasarlamak" },
  { Entzündet_Adj: "İltihaplı" },
  { Entzündung_Subst: "İltihap" },
  { Epilepsie_Subst: "Epilepsi" },
  { Epoche_Subst: "Çağ" },
  { Erbe_Subst: "Miras" },
  { Erbrechen_ReflVerb: "Kusmak" },
  { Erbringen_Verb: "Sağlamak (kanıt)" },
  { Erdöl_Subst: "Petrol" },
  { Erfolglos_Adj: "Başarısız" },
  { Erfolgreich_Adj: "Başarılı" },
  { Erforschen_Verb: "Araştırmak" },
  { Ergeben_ReflVerb: "Sonuçlanmak" },
  { Erhalt_Subst: "Koruma" },
  { Erhalten_Verb: "Almak" },
  { Erheben_Verb: "Toplamak (vergi)" },
  { Erkunden_ReflVerb: "Keşfetmek" },
  { Erlöschen_Verb: "Sönmek" },
  { Ermutigen_Verb: "Cesaretlendirmek" },
  { Erobern_Verb: "Fethetmek" },
  { Eroberung_Subst: "Fetih" },
  { Erpressung_Subst: "Şantaj" },
  { Erschließen_ReflVerb: "Geliştirmek (alan)" },
  { Erschrecken_ReflVerb: "Ürkmek" },
  { Erstatten_Verb: "Geri ödemek" },
  { Erstaunen_Subst: "Şaşkınlık" },
  { Erstehen_Verb: "Dirilmek" },
  { Erstsemester_Subst: "Birinci sınıf öğrencisi" },
  { Erwerben_Verb: "Kazanmak" },
  { Erzeugen_Verb: "Üretmek" },
  { Erzielen_Verb: "Elde etmek" },
  { Ethnisch_Adj: "Etnik" },
  { Evangelisch_Adj: "Protestan" },
  { Experiment_Subst: "Deney" },
  { Fachsprache_Subst: "Mesleki dil" },
  { Familienkreis_Subst: "Aile çevresi" },
  { Faszinierend_Adj: "Büyüleyici" },
  { Fehlermeldung_Subst: "Hata mesajı" },
  { Fehlschlagen_Verb: "Başarısız olmak" },
  { Fertigen_Verb: "Üretmek" },
  { Fertigung_Subst: "Üretim" },
  { Feststelltaste_Subst: "Caps Lock tuşu" },
  { fieberhaft_Adj: "Ateşli (çaba)" },
  { Flachbildfernseher_Subst: "LCD TV" },
  { flauschig_Adj: "Tüylü" },
  { Fleck_Subst: "Leke" },
  { flirten_ReflVerb: "Flört etmek" },
  { Flüchtling_Subst: "Mülteci" },
  { flüstern_Verb: "Fısıldamak" },
  { formulieren_Verb: "İfade etmek" },
  { freisetzen_Verb: "Serbest bırakmak" },
  { freistellen_Verb: "İzin vermek" },
  { Freundeskreis_Subst: "Arkadaş çevresi" },
  { Freundschaftsverhältnis_Subst: "Arkadaşlık ilişkisi" },
  { Frist_Subst: "Süre" },
  { fristgemäß_Adj: "Süresinde" },
  { fristgerecht_Adj: "Zamanında" },
  { Frust_Subst: "Hayal kırıklığı" },
  { Funde_Subst: "Bulgular" },
  { Funktion_Subst: "İşlev" },
  { fürchterlich_Adj: "Korkunç" },
  { Gänsehaut_Subst: "Tüylerin ürpermesi" },
  { gasförmig_Adj: "Gaz halinde" },
  { Gaszähler_Subst: "Gaz sayacı" },
  { geben_ReflVerb: "Teslim etmek" },
  { Gebrauch_Subst: "Kullanım" },
  { Geburtenrate_Subst: "Doğum oranı" },
  { Geburtshelfer_Subst: "Ebe" },
  { Geflüchtete_Subst: "Sığınmacı" },
  { gegenteilig_Adj: "Ters" },
  { Gegenüber_Subst: "Karşı taraf" },
  { gehören_ReflVerb: "Ait olmak" },
  { Geige_Subst: "Keman" },
  { Geist_Subst: "Ruh" },
  { geistig_Adj: "Zihinsel" },
  { geistlich_Adj: "Dini" },
  { Geistliche_Subst: "Din görevlisi" },
  { gelangen_Verb: "Ulaşmak" },
  { gelten_Verb: "Geçerli olmak" },
  { Gemälde_Subst: "Tablo" },
  { Gerichtsdiener_Subst: "Mahkeme memuru" },
  { Gerichtssaal_Subst: "Mahkeme salonu" },
  { Gerichtsverhandlung_Subst: "Duruşma" },
  { Geringfügigkeit_Subst: "Önemsizlik" },
  { Geringverdiener_Subst: "Düşük gelirli" },
  { Gerüst_Subst: "İskele" },
  { Geschirrspüler_Subst: "Bulaşık makinesi" },
  { Gesetzmäßigkeit_Subst: "Yasal düzen" },
  { Gesichtsausdruck_Subst: "Yüz ifadesi" },
  { Gesprächsstoff_Subst: "Sohbet konusu" },
  { gestalten_Verb: "Şekillendirmek" },
  { gestikulieren_Verb: "Jest yapmak" },
  { Getreide_Subst: "Tahıl" },
  { Gewebe_Subst: "Doku" },
  { Gewinde_Subst: "Vida dişi" },
  { Giftstoffe_Subst: "Zehirli maddeler" },
  { Glashaus_Subst: "Sera" },
  { Glaube_Subst: "İnanç" },
  { gläubig_Adj: "İnançlı" },
  { glaubwürdig_Adj: "Güvenilir" },
  { Gleichheit_Subst: "Eşitlik" },
  { Gletscher_Subst: "Buzul" },
  { glitschig_Adj: "Kaygan" },
  { grauenhaft_Adj: "Dehşet verici" },
  { grauenvoll_Adj: "Korkunç" },
  { Griff_Subst: "Tutamak" },
  { großartig_Adj: "Harika" },
  { Grundlage_Subst: "Temel" },
  { Grundsatz_Subst: "İlke" },
  { halten_Verb: "Tutmak" },
  { Handicap_Subst: "Engel" },
  { Handlung_Subst: "Eylem" },
  { Harnblase_Subst: "İdrar kesesi" },
  { hartnäckig_Adj: "İnatçı" },
  { Hauptfigur_Subst: "Baş karakter" },
  { Hausaufgaben_Subst: "Ev ödevi" },
  { Haushaltsartikel_Subst: "Ev eşyası" },
  { Hautfarbe_Subst: "Ten rengi" },
  { Hebamme_Subst: "Ebe" },
  { heftig_Adj: "Şiddetli" },
  { herausfinden_Verb: "Keşfetmek" },
  { herausgeben_Verb: "Yayınlamak" },
  { Herkunftsland_Subst: "Menşe ülke" },
  { Herrschaft_Subst: "İktidar" },
  { Herrscher_Subst: "Hükümdar" },
  { hervorragend_Adj: "Mükemmel" },
  { Herzklopfen_Subst: "Kalp çarpıntısı" },
  { hinbekommen_Verb: "Başarmak" },
  { hineinversetzen_Verb: "Kendini yerine koymak" },
  { hintergehen_Verb: "Aldatmak" },
  { hinzufügen_Verb: "Eklemek" },
  { Hochwasser_Subst: "Sel" },
  { Homophobie_Subst: "Homofobi" },
  { homosexuell_Adj: "Eşcinsel" },
  { Hülle_Subst: "Kılıf" },
  { identifizieren_Verb: "Tanımlamak" },
  { immatrikulieren_Refl_Verb: "Üniversiteye kaydolmak" },
  { Impfstoff_Subst: "Aşı" },
  { improvisieren_Verb: "Doğaçlama yapmak" },
  { Inanspruchnahme_Subst: "Talep" },
  { Industrialisierung_Subst: "Sanayileşme" },
  { industriell_Adj: "Endüstriyel" },
  { Industriestaat_Subst: "Sanayi ülkesi" },
  { Infektion_Subst: "Enfeksiyon" },
  { infizieren_Verb: "Enfekte etmek" },
  { inspirieren_Verb: "İlham vermek" },
  { Installationskunst_Subst: "Enstalasyon sanatı" },
  { instandhalten_Verb: "Bakım yapmak" },
  { interpretieren_Verb: "Yorumlamak" },
  { investieren_Verb: "Yatırım yapmak" },
  { jucken_Verb: "Kaşınmak" },
  { Jude_Subst: "Yahudi" },
  { Kaiser_Subst: "İmparator" },
  { kalkulieren_Verb: "Hesaplamak" },
  { Kanüle_Subst: "İğne" },
  { Kapazität_Subst: "Kapasite" },
  { Karikatur_Subst: "Karikatür" },
  { Katastrophe_Subst: "Felaket" },
  { katholisch_Adj: "Katolik" },
  { kaufmännisch_Adj: "Ticari" },
  { Keramik_Subst: "Seramik" },
  { Kerosin_Subst: "Gazyağı" },
  { Kittel_Subst: "Önlük" },
  { klatschen_Verb: "Alkışlamak" },
  { klebrig_Adj: "Yapışkan" },
  { Klimawandel_Subst: "İklim değişikliği" },
  { Knochenbruch_Subst: "Kemik kırığı" },
  { Kohle_Subst: "Kömür" },
  { Kohleausstieg_Subst: "Kömürden çıkış" },
  { Kohlenstoffdioxid_Subst: "Karbondioksit" },
  { Kolonialzeit_Subst: "Sömürge dönemi" },
  { Kommissar_Subst: "Komiser" },
  { kommunizieren_Verb: "İletişim kurmak" },
  { komplex_Adj: "Karmaşık" },
  { kondensieren_Verb: "Yoğunlaştırmak" },
  { Konfession_Subst: "Mezhep" },
  { konfrontieren_Verb: "Yüzleştirmek" },
  { Königreich_Subst: "Krallık" },
  { konkret_Adj: "Somut" },
  { konstant_Adj: "Sabit" },
  { Kork_Subst: "Mantar" },
  { Körpersprache_Subst: "Beden dili" },
  { kratzig_Adj: "Tırmalayıcı" },
  { Kreislauf_Subst: "Dolaşım" },
  { Kunstgeschichte_Subst: "Sanat tarihi" },
  { Kunstwerk_Subst: "Sanat eseri" },
  { Kuscheltier_Subst: "Peluş oyuncak" },
  { Ladezeit_Subst: "Şarj süresi" },
  { langatmig_Adj: "Uzun soluklu" },
  { lästig_Adj: "Can sıkıcı" },
  { Latein_Subst: "Latince" },
  { Laufzeit_Subst: "Süre (sözleşme)" },
  { lebendig_Adj: "Canlı" },
  { Lebenserwartung_Subst: "Yaşam beklentisi" },
  { lebensgefährlich_Adj: "Hayati tehlike" },
  { Lebenshaltungskosten_Subst: "Geçim maliyeti" },
  { Lebensraum_Subst: "Yaşam alanı" },
  { Lebensstandard_Subst: "Yaşam standardı" },
  { Lebensweise_Subst: "Yaşam tarzı" },
  { lebenswichtig_Adj: "Hayati" },
  { Leber_Subst: "Karaciğer" },
  { Lebewesen_Subst: "Canlı" },
  { Lehre_Subst: "Öğreti" },
  { Lehrveranstaltung_Subst: "Ders" },
  { Leinwand_Subst: "Tuval" },
  { leisten_Verb: "Başarmak" },
  { Leistung_Subst: "Performans" },
  { Liebesverhältnis_Subst: "Aşk ilişkisi" },
  { literarisch_Adj: "Edebi" },
  { löffeln_Verb: "Kaşıkla almak" },
  { lohnen_Refl_Verb: "Değmek" },
  { Lösegeld_Subst: "Fidye" },
  { lösen_Refl_Verb: "Çözmek" },
  { loswerden_Verb: "Kurtulmak" },
  { Lunge_Subst: "Akciğer" },
  { Lungenentzündung_Subst: "Zatürre" },
  { Malerei_Subst: "Resim sanatı" },
  { Marmor_Subst: "Mermer" },
  { Maschinenbau_Subst: "Makine mühendisliği" },
  { Masse_Subst: "Kütle" },
  { Massentierhaltung_Subst: "Fabrika çiftçiliği" },
  { Materie_Subst: "Madde" },
  { materiell_Adj: "Maddi" },
  { Mauerfall_Subst: "Duvarın yıkılışı" },
  { Mauerwerk_Subst: "Duvar işçiliği" },
  { mehrsprachig_Adj: "Çok dilli" },
  { Mehrsprachigkeit_Subst: "Çok dillilik" },
  { meisterhaft_Adj: "Usta işi" },
  { meistern_Verb: "Üstesinden gelmek" },
  { Menschenrecht_Subst: "İnsan hakkı" },
  { Methan_Subst: "Metan" },
  { Migrationshintergrund_Subst: "Göçmen köken" },
  { Mikroplastik_Subst: "Mikroplastik" },
  { Mikrowelle_Subst: "Mikrodalga" },
  { Milchprodukt_Subst: "Süt ürünü" },
  { Militär_Subst: "Ordu" },
  { Minderheit_Subst: "Azınlık" },
  { missachten_Verb: "Görmezden gelmek" },
  { missbrauchen_Verb: "Kötüye kullanmak" },
  { missfallen_Verb: "Hoşlanmamak" },
  { misstrauen_Verb: "Güvenmemek" },
  { missverstehen_Verb: "Yanlış anlamak" },
  { Mittelalter_Subst: "Orta Çağ" },
  { mittelalterlich_Adj: "Orta Çağ’a ait" },
  { Mittelschicht_Subst: "Orta sınıf" },
  { mittelständisch_Adj: "Orta ölçekli" },
  { mitwirken_Verb: "Katkıda bulunmak" },
  { Mitwirkungspflicht_Subst: "İşbirliği zorunluluğu" },
  { Moderne_Subst: "Modernite" },
  { Molekül_Subst: "Molekül" },
  { Monarchie_Subst: "Monarşi" },
  { montieren_Verb: "Montaj yapmak" },
  { Mörder_Subst: "Katil" },
  { Mosaik_Subst: "Mozaik" },
  { multikulturell_Adj: "Çok kültürlü" },
  { Musical_Subst: "Müzikal" },
  { Muslim_Subst: "Müslüman" },
  { Nachbarschaft_Subst: "Komşuluk" },
  { nachfragen_Verb: "Sormak" },
  { nachhaken_Verb: "Üstelemek" },
  { nachhaltig_Adj: "Sürdürülebilir" },
  { Nachhaltigkeit_Subst: "Sürdürülebilirlik" },
  { nachkommen_Verb: "Yerine getirmek" },
  { Nachkriegszeit_Subst: "Savaş sonrası dönem" },
  { nachreichen_Verb: "Sonradan sunmak" },
  { Nächstenliebe_Subst: "Komşu sevgisi" },
  { nachvollziehen_Verb: "Anlamak" },
  { Nachweis_Subst: "Kanıt" },
  { nachweisen_Verb: "Kanıtlamak" },
  { nackt_Adj: "Çıplak" },
  { Nährstoff_Subst: "Besin maddesi" },
  { Nahrungskreislauf_Subst: "Besin zinciri" },
  { Nationalität_Subst: "Milliyet" },
  { Nationalsozialismus_Subst: "Nasyonal sosyalizm" },
  { Nationalstaat_Subst: "Ulus devlet" },
  { Neid_Subst: "Kıskançlık" },
  { neidisch_Adj: "Kıskanç" },
  { nerven_Verb: "Sinir etmek" },
  { nervlich_Adj: "Sinirsel" },
  { neurologisch_Adj: "Nörolojik" },
  { Neuzeit_Subst: "Yeni Çağ" },
  { nicken_Verb: "Başını sallamak" },
  { niederlassen_Verb: "Yerleşmek" },
  { Niederschrift_Subst: "Tutanak" },
  { Niere_Subst: "Böbrek" },
  { nüchtern_Adj: "Ayık" },
  { Nutzerfreundlichkeit_Subst: "Kullanıcı dostu" },
  { Oberfläche_Subst: "Yüzey" },
  { Oberhaupt_Subst: "Lider" },
  { offensichtlich_Adj: "Açık" },
  { Öffentlichkeit_Subst: "Kamuoyu" },
  { Ohrring_Subst: "Küpe" },
  { Ölfarbe_Subst: "Yağlı boya" },
  { optimieren_Verb: "Optimize etmek" },
  { Orchidee_Subst: "Orkide" },
  { ortsansässig_Adj: "Yerleşik" },
  { Pädagogik_Subst: "Pedagoji" },
  { Pantomime_Subst: "Pandomim" },
  { Papierkorb_Subst: "Çöp sepeti" },
  { Papst_Subst: "Papa" },
  { Passant_Subst: "Yaya" },
  { Pedal_Subst: "Pedal" },
  { personenbezogen_Adj: "Kişiye özel" },
  { Perspektive_Subst: "Perspektif" },
  { Pflegepersonal_Subst: "Bakım personeli" },
  { Physiotherapeut_Subst: "Fizyoterapist" },
  { Pilz_Subst: "Mantar" },
  { Pilzinfektion_Subst: "Mantar enfeksiyonu" },
  { Pinnwand_Subst: "Pano" },
  { Pinsel_Subst: "Fırça" },
  { Plädoyer_Subst: "Savunma konuşması" },
  { polieren_Verb: "Parlatmak" },
  { Polizeidirektion_Subst: "Polis müdürlüğü" },
  { Porträt_Subst: "Portre" },
  { Porzellan_Subst: "Porselen" },
  { Posten_Subst: "Görev" },
  { prägen_Verb: "Şekillendirmek" },
  { Preis_Leistungs_Verhältnis_Subst: "Fiyat-performans oranı" },
  { Prinzip_Subst: "İlke" },
  { Proband_Subst: "Denek" },
  { proben_Verb: "Prova yapmak" },
  { Prognose_Subst: "Tahmin" },
  { programmieren_Verb: "Programlamak" },
  { Psychologe_Subst: "Psikolog" },
  { psychologisch_Adj: "Psikolojik" },
  { Puls_Subst: "Nabız" },
  { Puppentheater_Subst: "Kukla tiyatrosu" },
  { Putzlappen_Subst: "Bez" },
  { Quelle_Subst: "Kaynak" },
  { Radiergummi_Subst: "Silgi" },
  { Radioaktivität_Subst: "Radyoaktivite" },
  { Rahmen_Subst: "Çerçeve" },
  { Randgebiet_Subst: "Kenar bölge" },
  { Rasse_Subst: "Irk" },
  { Rassismus_Subst: "Irkçılık" },
  { raten_Verb: "Tavsiye etmek" },
  { rau_Adj: "Pürüzlü" },
  { Rauschgift_Subst: "Uyuşturucu" },
  { Rechtsbehelfsbelehrung_Subst: "Hukuki yol bilgilendirmesi" },
  { reflektieren_Verb: "Yansıtmak" },
  { Reform_Subst: "Reform" },
  { Reformation_Subst: "Reformasyon" },
  { reformieren_Verb: "Yeniden düzenlemek" },
  { Regenwald_Subst: "Yağmur ormanı" },
  { reiben_Verb: "Ovmak" },
  { religiös_Adj: "Dini" },
  { Rentenversicherung_Subst: "Emeklilik sigortası" },
  { Ressource_Subst: "Kaynak" },
  { ringen_Verb: "Güreşmek" },
  { Rohstoff_Subst: "Ham madde" },
  { römisch_Adj: "Roma’ya ait" },
  { Röntgenaufnahme_Subst: "Röntgen görüntüsü" },
  { Rückgang_Subst: "Düşüş" },
  { Rückstand_Subst: "Geri kalma" },
  { Rückzahlungsverpflichtung_Subst: "Geri ödeme yükümlülüğü" },
  { Ruf_Subst: " Ün" },
  { Sachverhalt_Subst: "Olgu" },
  { Säge_Subst: "Testere" },
  { Sauerstoff_Subst: "Oksijen" },
  { Schadensersatzanspruch_Subst: "Tazminat talebi" },
  { Schadstoff_Subst: "Zararlı madde" },
  { Schäferhund_Subst: "Çoban köpeği" },
  { scheitern_Verb: "Başarısız olmak" },
  { Schicht_Subst: "Vardiya" },
  { Schiene_Subst: "Ray" },
  { schildern_Verb: "Betimlemek" },
  { Schilderung_Subst: "Tasvir" },
  { Schlagzeug_Subst: "Bateri" },
  { schlucken_Verb: "Yutmak" },
  { schmelzen_Verb: "Erimek" },
  { schmerzhaft_Adj: "Acı verici" },
  { Schornsteinfeger_Subst: "Baca temizleyicisi" },
  { Schraube_Subst: "Vida" },
  { Schraubendreher_Subst: "Tornavida" },
  { Schublade_Subst: "Çekmece" },
  { Schulstoff_Subst: "Ders müfredatı" },
  { schütteln_Refl_Verb: "Sallamak" },
  { Schwerkraft_Subst: "Yer çekimi" },
  { Schwindel_Subst: "Baş dönmesi" },
  { schwinden_Verb: "Azalmak" },
  { Seelsorger_Subst: "Din görevlisi" },
  { Sehne_Subst: "Tendon" },
  { Sehnsucht_Subst: "Özlem" },
  { sicherstellen_Verb: "Garantiye almak" },
  { Sicherung_Subst: "Sigorta" },
  { signalisieren_Verb: "İşaret vermek" },
  { Silber_Subst: "Gümüş" },
  { Skulptur_Subst: "Heykel" },
  { Solidarität_Subst: "Dayanışma" },
  { Sonnenstrahl_Subst: "Güneş ışını" },
  { sonstig_Adj: "Diğer" },
  { Sowjetunion_Subst: "Sovyetler Birliği" },
  { Soziologie_Subst: "Sosyoloji" },
  { spalten_Verb: "Bölmek" },
  { Spannung_Subst: "Gerilim" },
  { spenden_Verb: "Bağışlamak" },
  { spezifisch_Adj: "Özgül" },
  { Spitzer_Subst: "Kalemtraş" },
  { Spracherwerb_Subst: "Dil edinimi" },
  { Sprachwissenschaft_Subst: "Dil bilimi" },
  { Sprichwort_Subst: "Atasözü" },
  { Springseil_Subst: "Atlama ipi" },
  { Spülmaschine_Subst: "Bulaşık makinesi" },
  { Spur_Subst: "İz" },
  { Staatsangehörigkeit_Subst: "Vatandaşlık" },
  { Staatsanwalt_Subst: "Savcı" },
  { stabil_Adj: "Sağlam" },
  { Stadtkern_Subst: "Şehir merkezi" },
  { Stadtrand_Subst: "Şehir çeperi" },
  { Stadtstaat_Subst: "Şehir devleti" },
  { Stand_Subst: "Durum" },
  { Stationsleiter_Subst: "İstasyon şefi" },
  { stattgeben_Verb: "Kabul etmek (dilekçe)" },
  { Stellenanzeige_Subst: "İş ilanı" },
  { Sterblichkeit_Subst: "Ölüm oranı" },
  { Stimmlage_Subst: "Ses tonu" },
  { Stoff_Subst: "Kumaş" },
  { störungsfrei_Adj: "Sorunsuz" },
  { Straftat_Subst: "Suç" },
  { strahlen_Verb: "Işık saçmak" },
  { Straßenverkehrsordnung_Subst: "Trafik kuralları" },
  { streichen_Verb: "Çizmek" },
  { Stromschlag_Subst: "Elektrik çarpması" },
  { Stromzähler_Subst: "Elektrik sayacı" },
  { Studiengang_Subst: "Bölüm (üniversite)" },
  { Studiensekretariat_Subst: "Öğrenci işleri" },
  { Stuhlprobe_Subst: "Dışkı örneği" },
  { Substanz_Subst: "Madde" },
  { Symptom_Subst: "Belirti" },
  { Tabu_Subst: "Tabu" },
  { Tagung_Subst: "Konferans" },
  { Tapete_Subst: "Duvar kağıdı" },
  { tapezieren_Verb: "Duvar kağıdı yapıştırmak" },
  { tätig_Adj: "Faal" },
  { Tatort_Subst: "Olay yeri" },
  { Teilgebiet_Subst: "Alt alan" },
  { Teilhabe_Subst: "Katılım" },
  { teilhaben_Verb: "Katılmak" },
  { Teilung_Subst: "Bölünme" },
  { Themenspektrum_Subst: "Konu yelpazesi" },
  { Thermostat_Subst: "Termostat" },
  { These_Subst: "Tez" },
  { tolerieren_Verb: "Hoş görmek" },
  { Ton_Subst: "Kil" },
  { Tracht_Subst: "Geleneksel kıyafet" },
  { trauen_Verb: "Güvenmek" },
  { traumhaft_Adj: "Rüya gibi" },
  { Treibhauseffekt_Subst: "Sera etkisi" },
  { Treibstoff_Subst: "Yakıt" },
  { Trompete_Subst: "Trompet" },
  { tropfen_Verb: "Damlamak" },
  { Trost_Subst: "Teselli" },
  { trösten_Verb: "Teselli etmek" },
  { Tupfer_Subst: "Pamuklu çubuk" },
  { übel_Adj: "Kötü" },
  { überbewerten_Verb: "Abartmak" },
  { überdenken_Verb: "Yeniden düşünmek" },
  { übereinstimmen_Verb: "Aynı fikirde olmak" },
  { Überfall_Subst: "Baskın" },
  { überfordern_Verb: "Zorlamak" },
  { Übergang_Subst: "Geçiş" },
  { übergehen_Verb: "Atlatmak" },
  { überliefern_Verb: "Aktarmak" },
  { übernehmen_Verb: "Devralmak" },
  { überschätzen_Verb: "Gözünde büyütmek" },
  { überschwemmen_Verb: "Su basmak" },
  { Überschwemmung_Subst: "Sel" },
  { überstehen_Verb: "Atlatmak" },
  { übertragbar_Adj: "Bulaşıcı" },
  { übertreiben_Verb: "Abartmak" },
  { überwachen_Verb: "Gözetlemek" },
  { üblich_Adj: "Alışılagelmiş" },
  { Ultraschallbild_Subst: "Ultrason görüntüsü" },
  { Ultraschalluntersuchung_Subst: "Ultrason muayenesi" },
  { umfassen_Verb: "Kapsamak" },
  { umgeben_Verb: "Çevrelemek" },
  { umgehend_Adj: "Acil" },
  { Umstand_Subst: "Durum" },
  { Umstellung_Subst: "Uyum sağlama" },
  { Umstieg_Subst: "Geçiş" },
  { umwandeln_Verb: "Dönüştürmek" },
  { Umwandlung_Subst: "Dönüşüm" },
  { unangemessen_Adj: "Uygunsuz" },
  { unbegründet_Adj: "Dayanaksız" },
  { unglaubwürdig_Adj: "Güvenilmez" },
  { Ungleichheit_Subst: "Eşitsizlik" },
  { Ungleichverteilung_Subst: "Dengesiz dağılım" },
  { unterbewerten_Verb: "Hafife almak" },
  { unterbringen_Verb: "Yerleştirmek" },
  { unterfordern_Verb: "Altında kalmak" },
  { unterschätzen_Verb: "Hafife almak" },
  { untertreiben_Verb: "Küçümsemek" },
  { Urin_Subst: "İdrar" },
  { Urinprobe_Subst: "İdrar örneği" },
  { Vene_Subst: "Toplardamar" },
  { Ventil_Subst: "Valf" },
  { veranschaulichen_Verb: "Örneklendirmek" },
  { veranstalten_Verb: "Düzenlemek" },
  { verbauen_Verb: "Engel olmak" },
  { verbeugen_Refl_Verb: "Eğilmek" },
  { verbreiten_Verb: "Yaymak" },
  { Verbrennungsmotor_Subst: "İçten yanmalı motor" },
  { verbunden_sein_Verb: "Bağlı olmak" },
  { Verdächtige_Subst: "Şüpheli" },
  { verdampfen_Verb: "Buharlaşmak" },
  { Verdauung_Subst: "Sindirim" },
  { Vererbung_Subst: "Kalıtım" },
  { verfassen_Verb: "Yazmak (metin)" },
  { verfilmen_Verb: "Filme uyarlamak" },
  { Verhältnis_Subst: "Oran" },
  { verheimlichen_Verb: "Gizlemek" },
  { Verjährungsfrist_Subst: "Zamanaşımı süresi" },
  { Verkehrswende_Subst: "Ulaşım dönüşümü" },
  { verkünden_Verb: "İlan etmek" },
  { verlegen_Verb: "Ertelemek" },
  { Verlegenheit_Subst: "Mahcubiyet" },
  { vermitteln_Verb: "Aracılık etmek" },
  { Vermögen_Subst: "Servet" },
  { vernachlässigen_Verb: "İhmal etmek" },
  { vernehmen_Verb: "İfade almak" },
  { Vernehmung_Subst: "İfade alma" },
  { Vernunft_Subst: "Akıl" },
  { versagen_Verb: "Başarısız olmak" },
  { verschieben_Verb: "Ertelemek" },
  { verschlagen_Verb: "Şaşırtmak" },
  { verschwenden_Verb: "İsraf etmek" },
  { versorgen_Verb: "Bakmak" },
  { verstärken_Refl_Verb: "Güçlenmek" },
  { verstauen_Verb: "Yerleştirmek" },
  { Verstoß_Subst: "İhlal" },
  { verstoßen_Verb: "İhlal etmek" },
  { verteidigen_Verb: "Savunmak" },
  { Verteidiger_Subst: "Savunma avukatı" },
  { Verteilung_Subst: "Dağıtım" },
  { Vertrauensverhältnis_Subst: "Güven ilişkisi" },
  { Vertreibung_Subst: "Sürgün" },
  { vertreten_Verb: "Temsil etmek" },
  { Verwaltungsgericht_Subst: "İdare mahkemesi" },
  { Verwandtschaft_Subst: "Akrabalık" },
  { verweigern_Verb: "Reddetmek" },
  { verwundet_Adj: "Yaralı" },
  { verziehen_Verb: "Eğilmek" },
  { Verzweiflung_Subst: "Umutsuzluk" },
  { Violine_Subst: "Keman" },
  { Visite_Subst: "Vizite" },
  { Völkerwanderung_Subst: "Kavimler göçü" },
  { Volkswirtschaft_Subst: "Ulusal ekonomi" },
  { Vorfahr_Subst: "Atalar" },
  { Vorgang_Subst: "Süreç" },
  { Vorhersage_Subst: "Tahmin" },
  { vorhersehbar_Adj: "Öngörülebilir" },
  { vorlegen_Verb: "Sunmak" },
  { vorsprechen_Verb: "Dinletmek" },
  { vorstellen_Refl_Verb: "Tanıştırmak" },
  { vorwerfen_Verb: "Suçlamak" },
  { vorzeitig_Adj: "Erken" },
  { Wachstum_Subst: "Büyüme" },
  { warten_Verb: "Beklemek" },
  { Wäschetrockner_Subst: "Çamaşır kurutma makinesi" },
  { Wasserdampf_Subst: "Su buharı" },
  { Wasserspiegel_Subst: "Su seviyesi" },
  { Wechselwirkung_Subst: "Etkileşim" },
  { wegdrehen_Verb: "Çevirmek" },
  { wegschmeißen_Verb: "Atmak" },
  { Wegwerfprodukt_Subst: "Tek kullanımlık ürün" },
  { weiterbilden_Refl_Verb: "Kendini geliştirmek" },
  { weltlich_Adj: "Dünyevi" },
  { Werkstoff_Subst: "Malzeme" },
  { widerlegen_Verb: "Çürütmek" },
  { widerspiegeln_Verb: "Yansıtmak" },
  { wiedergeben_Verb: "Geri vermek" },
  { Wiederherstellung_Subst: "Yeniden yapılandırma" },
  { Wiedervereinigung_Subst: "Yeniden birleşme" },
  { wiederverwenden_Verb: "Yeniden kullanmak" },
  { Wirtschaftswunder_Subst: "Ekonomik mucize" },
  { wischen_Verb: "Silmek" },
  { Wohlstand_Subst: "Refah" },
  { wundervoll_Adj: "Harika" },
  { Würde_Subst: "Onur" },
  { Wurzel_Subst: "Kök" },
  { Wut_Subst: "Öfke" },
  { Zähler_Subst: "Sayaç" },
  { Zählerstand_Subst: "Sayaç okuması" },
  { Zahlungseingang_Subst: "Ödeme alındı" },
  { Zelle_Subst: "Hücre" },
  { zerdrücken_Verb: "Ezmek" },
  { Zerfall_Subst: "Çözülme" },
  { zerfallen_Verb: "Parçalanmak" },
  { zerschlagen_Verb: "Parçalamak" },
  { Ziehharmonika_Subst: "Akordeon" },
  { Zielland_Subst: "Hedef ülke" },
  { Zimmertemperatur_Subst: "Oda sıcaklığı" },
  { zitieren_Verb: "Alıntı yapmak" },
  { zittern_Verb: "Titremek" },
  { zucken_Verb: "Seğirmek" },
  { zugutekommen_Verb: "Fayda sağlamak" },
  { Zulassung_Subst: "Onay" },
  { zulassungsfrei_Adj: "Kayıt koşulsuz" },
  { zulegen_Refl_Verb: "Hızlanmak" },
  { zunehmen_Verb: "Artmak" },
  { zurechtfinden_Verb: "Yolunu bulmak" },
  { zurechtkommen_Verb: "Başa çıkmak" },
  { zurückgehen_Verb: "Gerilemek" },
  { zusammensetzen_Refl_Verb: "Oluşmak" },
  { zustande_bringen_Verb: "Başarmak" },
  { zutrauen_Refl_Verb: "Güvenmek" },
  { zuwenden_Verb: "Yönelmek" },
];
export default err;
