const germanVerbs = {
  sehen: {
    meaning: "görmek",
    prefixes: {
      absehen: "öngörmek, tahmin etmek",
      ansehen: "bakmak, izlemek",
      aufsehen: "yukarı bakmak",
      aussehen: "görünmek",
      besehen: "incelemek",
      durchsehen: "göz gezdirmek, kontrol etmek",
      einsehen: "kabul etmek, anlamak",
      ersehen: "anlamak, çıkarmak",
      fersehen: "uzaktaki bir şeyi görmek",
      hersehen: "buraya bakmak",
      hinsehen: "bakmak, dikkat etmek",
      mitsehen: "birlikte izlemek",
      nachsehen: "kontrol etmek, bakmak",
      übersehen: "gözden kaçırmak, görmemek",
      umsehen: "etrafına bakmak",
      versehen: "donatmak",
      vorsehen: "öngörmek, planlamak",
      wegsehen: "başka tarafa bakmak",
      wiedersehen: "tekrar görmek, tekrar buluşmak",
      zusehen: "izlemek, seyretmek",
    },
  },

  gehen: {
    meaning: "gitmek",
    prefixes: {
      abgehen: "ayrılmak, çıkmak",
      angehen: "yaklaşmak, ilgilendirmek",
      aufgehen: "açılmak, doğmak (güneş)",
      ausgehen: "dışarı çıkmak, sönmek",
      begehen: "kutlamak, işlemek (suç)",
      durchgehen: "geçmek, gözden geçirmek",
      eingehen: "içeri girmek, kabul etmek",
      entgehen: "kaçırmak, kurtulmak",
      hinausgehen: "dışarı çıkmak",
      nachgehen: "peşinden gitmek, takip etmek",
      übergehen: "geçmek, atlamak",
      umgehen: "dolaşmak, baş etmek",
      vergehen: "geçmek (zaman)",
      vorgehen: "öne çıkmak, ilerlemek",
      zugehen: "yaklaşmak",
    },
  },

  kommen: {
    meaning: "gelmek",
    prefixes: {
      abkommen: "sapmak, ayrılmak",
      ankommen: "varmak, gelmek",
      aufkommen: "ortaya çıkmak, üstlenmek",
      auskommen: "geçinmek, idare etmek",
      bekommen: "almak, elde etmek",
      durchkommen: "geçmek, başarmak",
      einkommen: "içeri girmek, gelir elde etmek",
      entkommen: "kaçmak, kurtulmak",
      herkommen: "buraya gelmek, kökeni olmak",
      hinkommen: "oraya gitmek, ulaşmak",
      mitkommen: "birlikte gelmek",
      nachkommen: "takip etmek, yerine getirmek",
      überkommen: "kapılmak, üstesinden gelmek",
      umkommen: "ölmek, telef olmak",
      vorkommen: "meydana gelmek, görülmek",
      wegkommen: "uzaklaşmak, kurtulmak",
      zurückkommen: "geri gelmek",
    },
  },

  machen: {
    meaning: "yapmak",
    prefixes: {
      abmachen: "anlaşmak, çıkarmak",
      anmachen: "açmak (cihaz), baştan çıkarmak",
      aufmachen: "açmak (kapı, paket)",
      ausmachen: "kapatmak, oluşturmak, fark etmek",
      bemachen: "kirletmek (nadir)",
      durchmachen: "katlanmak, geçirmek (zor bir süreç)",
      einmachen: "konserve yapmak",
      fertigmachen: "tamamlamak, bitirmek",
      herausmachen: "çıkarmak, anlamak",
      hinmachen: "oraya götürmek, başarmak",
      kaputtmachen: "bozmak, kırmak",
      mitmachen: "katılmak, eşlik etmek",
      nachmachen: "taklit etmek, kopyalamak",
      übermachen: "devretmek, hediye etmek",
      untermachen: "aldatmak, sabote etmek",
      vermachen: "miras bırakmak",
      vormachen: "göstermek, kandırmak",
      weitermachen: "devam etmek",
      zumachen: "kapatmak (kapı, pencere)",
    },
  },

  geben: {
    meaning: "vermek",
    prefixes: {
      abgeben: "teslim etmek, bırakmak",
      angeben: "belirtmek, övünmek",
      aufgeben: "vazgeçmek, teslim etmek (posta)",
      ausgeben: "harcamak, yayınlamak",
      begeben: "gitmek, kendini adamak",
      durchgeben: "iletmek, aktarmak",
      eingeben: "girmek (veri), sunmak",
      herausgeben: "yayınlamak, geri vermek",
      hergeben: "vermek, feda etmek",
      hingeben: "kendini adamak, teslim olmak",
      mitgeben: "birlikte vermek, eklemek",
      nachgeben: "boyun eğmek, esnemek",
      übereingeben: "devretmek, teslim etmek",
      vergeben: "affetmek, dağıtmak",
      vorgeben: "iddia etmek, öne sürmek",
      weitergeben: "aktarmak, devretmek",
      zurückgeben: "geri vermek, iade etmek",
    },
  },

  nehmen: {
    meaning: "almak",
    prefixes: {
      abnehmen: "çıkarmak, kilo vermek",
      annehmen: "kabul etmek, varsaymak",
      aufnehmen: "kaydetmek, almak (misafir)",
      ausnehmen: "içini boşaltmak, kazıklamak",
      benehmen: "davranmak, terbiyeli olmak",
      durchnehmen: "gözden geçirmek, ele almak",
      einnehmen: "almak (ilaç), kazanmak",
      entnehmen: "çıkarmak, anlamak",
      herausnehmen: "dışarı çıkarmak",
      hinnehmen: "kabul etmek, katlanmak",
      mitnehmen: "yanında götürmek, almak",
      nachnehmen: "tekrar almak, örnek almak",
      übernehmen: "devralmak, üstlenmek",
      unternehmen: "girişimde bulunmak",
      vernehmen: "duymak, sorgulamak",
      vornehmen: "planlamak, karar vermek",
      wegnehmen: "almak, elinden almak",
      zunehmen: "kilo almak, artmak",
    },
  },

  stehen: {
    meaning: "durmak",
    prefixes: {
      abstehen: "dışarı çıkmak, uzak durmak",
      anstehen: "kuyrukta beklemek, yakışmak",
      aufstehen: "ayağa kalkmak, uyanmak",
      ausstehen: "beklemek (bir şeyin), dayanmak",
      bestehen: "var olmak, geçmek (sınav)",
      durchstehen: "dayanmak, atlatmak",
      einstehen: "kefil olmak, savunmak",
      entstehen: "ortaya çıkmak, oluşmak",
      herstehen: "buraya gelmek, hazır olmak",
      hinausstehen: "dışarı sarkmak",
      mitstehen: "eşlik etmek, dayanmak",
      nachstehen: "geri kalmak, aşağı olmak",
      überstehen: "atlatmak, üstesinden gelmek",
      umstehen: "etrafta durmak",
      verstehen: "anlamak, idrak etmek",
      vorstehen: "başkanlık etmek, çıkıntı yapmak",
      wegstehen: "yoldan çekilmek",
      zustehen: "hak etmek, uygun olmak",
    },
  },

  lassen: {
    meaning: "bırakmak, izin vermek",
    prefixes: {
      ablassen: "boşaltmak, bırakmak",
      anlassen: "çalıştırmak (motor), açık bırakmak",
      auflassen: "açmak, bırakmak (kapı)",
      auslassen: "dışarı çıkarmak, atlamak",
      belassen: "olduğu gibi bırakmak",
      durchlassen: "geçmesine izin vermek",
      einlassen: "içeri almak, sokmak",
      entlassen: "işten çıkarmak, serbest bırakmak",
      herauslassen: "dışarı salmak, açıklamak",
      hinlassen: "oraya bırakmak, ihmal etmek",
      mitlassen: "birlikte götürmek, dahil etmek",
      nachlassen: "azalmak, gevşemek",
      überlassen: "devretmek, bırakmak",
      unterlassen: "yapmaktan kaçınmak",
      verlassen: "terk etmek, ayrılmak",
      vorlassen: "öne bırakmak, öncelik vermek",
      weglassen: "çıkarmak, atlamak",
      zulassen: "izin vermek, kabul etmek",
    },
  },

  sprechen: {
    meaning: "konuşmak",
    prefixes: {
      absprechen: "anlaşmak, kararlaştırmak",
      ansprechen: "hitap etmek, konu açmak",
      aufsprechen: "kaydetmek (ses), konuşmak",
      aussprechen: "telaffuz etmek, açıkça söylemek",
      besprechen: "tartışmak, görüşmek",
      durchsprechen: "detaylıca konuşmak",
      einsprechen: "ses kaydetmek, araya girmek",
      entgegensprechen: "karşı çıkmak, çelişmek",
      hersprechen: "buraya gelip konuşmak",
      mitsprechen: "konuşmaya katılmak",
      nachsprechen: "tekrar etmek, taklit etmek",
      übersprechen: "üstüne konuşmak, çevirmek",
      versprechen: "söz vermek, yanlış söylemek",
      voraussprechen: "önceden konuşmak",
      vorsprechen: "deneme yapmak (oyunculuk), konuşmak",
      weitersprechen: "konuşmaya devam etmek",
      zusprechen: "cesaretlendirmek, ikna etmek",
    },
  },

  schreiben: {
    meaning: "yazmak",
    prefixes: {
      abschreiben: "kopya çekmek, yazarak çıkarmak",
      anschreiben: "yazmak (birine), borç yazmak",
      aufschreiben: "not almak, yazmak",
      ausschreiben: "ilan etmek, tam yazmak",
      beschreiben: "tarif etmek, betimlemek",
      durchschreiben: "kopyasını çıkarmak, devamlı yazmak",
      einschreiben: "kaydetmek, taahhütlü göndermek",
      fortschreiben: "devam ettirmek, güncellemek",
      herschreiben: "buraya yazmak",
      hinschreiben: "oraya yazmak, aceleyle yazmak",
      mitschreiben: "not almak, birlikte yazmak",
      nachschreiben: "tekrar yazmak, kopya etmek",
      überschreiben: "üzerine yazmak, devretmek",
      umschreiben: "yeniden yazmak, dolaylı ifade etmek",
      verschreiben: "reçete yazmak, yanlış yazmak",
      vorschreiben: "emretmek, dikte etmek",
      weiterschreiben: "yazmaya devam etmek",
      zuschreiben: "atfetmek, birine yazmak",
    },
  },

  finden: {
    meaning: "bulmak",
    prefixes: {
      abfinden: "razı olmak, yetinmek",
      anfinden: "başlamak (nadir), bulmaya başlamak",
      auffinden: "bulmak, keşfetmek",
      ausfinden: "öğrenmek, keşfetmek",
      befinden: "bulunmak, olmak (durum)",
      durchfinden: "geçmek, yolunu bulmak",
      einfinden: "alışmak, uyum sağlamak",
      erfinden: "icat etmek, uydurmak",
      herausfinden: "öğrenmek, keşfetmek",
      hinfinden: "razı olmak, katlanmak",
      mitfinden: "birlikte bulmak",
      nachfinden: "aramak, izini sürmek",
      stattfinden: "gerçekleşmek, yapılmak",
      überfinden: "şaşırmak, düşünmek",
      verfinden: "kaybetmek, yitirmek (nadir)",
      vorfinden: "bulmak (bir şeyin olduğu gibi)",
      weiterfinden: "devam etmek, bulmaya devam etmek",
      zufinden: "tesadüfen bulmak",
    },
  },

  halten: {
    meaning: "tutmak, durdurmak",
    prefixes: {
      abhalten: "engellemek, düzenlemek (etkinlik)",
      anhalten: "durdurmak, devam etmek",
      aufhalten: "oyalamak, durdurmak",
      aushalten: "dayanmak, katlanmak",
      behalten: "saklamak, hatırlamak",
      durchhalten: "direnmek, devam etmek",
      einhalten: "uymak (kurala), durdurmak",
      enthalten: "içermek, kapsamak",
      erhalten: "almak, korumak",
      heraushalten: "dışarı uzatmak, dayanmak",
      hinhalten: "oyalamak, idare etmek",
      mithalten: "ayak uydurmak",
      nachhalten: "kin tutmak, sürdürmek",
      überhalten: "devam ettirmek, üstesinden gelmek",
      unterhalten: "eğlendirmek, sürdürmek",
      verhalten: "davranmak, tutum sergilemek",
      vorhalten: "sitem etmek, hazır tutmak",
      weiterhalten: "devam etmek",
      zurückhalten: "tutmak, engellemek",
    },
  },

  arbeiten: {
    meaning: "çalışmak",
    prefixes: {
      abarbeiten: "işleri bitirmek, tamamlamak",
      anarbeiten: "başlamak (bir işte), kaba iş yapmak",
      aufarbeiten: "işlemek, ele almak (konu)",
      ausarbeiten: "detaylandırmak, geliştirmek",
      bearbeiten: "işlemek, düzenlemek",
      durcharbeiten: "baştan sona çalışmak, gece çalışmak",
      einarbeiten: "alışmak (işe), öğrenmek",
      erarbeiten: "kazanmak, elde etmek (çaba ile)",
      herausarbeiten: "ortaya çıkarmak, vurgulamak",
      mitarbeiten: "katkıda bulunmak, birlikte çalışmak",
      nacharbeiten: "eksik işleri tamamlamak",
      überarbeiten: "gözden geçirmek, fazla çalışmak",
      verarbeiten: "işlemek (malzeme), başa çıkmak",
      vorarbeiten: "önceden çalışmak, hazırlık yapmak",
      weiterarbeiten: "çalışmaya devam etmek",
      zusammenarbeiten: "işbirliği yapmak",
    },
  },

  ziehen: {
    meaning: "çekmek, taşınmak",
    prefixes: {
      abziehen: "çekip çıkarmak, soyulmak",
      anziehen: "giymek, çekmek (dikkat)",
      aufziehen: "açmak, büyütmek (çocuk)",
      ausziehen: "çıkarmak (giysi), taşınmak",
      beziehen: "kaplamak, referans yapmak",
      durchziehen: "tamamlamak, geçirmek",
      einziehen: "içeri çekmek, taşınmak",
      entziehen: "çekip almak, kaçmak",
      erziehen: "yetiştirmek, eğitmek",
      herausziehen: "dışarı çekmek, uzatmak",
      herziehen: "buraya çekmek, göç etmek",
      hinziehen: "uzatmak, oyalanmak",
      mitziehen: "birlikte çekmek, eşlik etmek",
      nachziehen: "takip etmek, sıkılaştırmak",
      überziehen: "kaplamak, aşmak (süre)",
      umziehen: "taşınmak, kıyafet değiştirmek",
      verziehen: "çarpıtmak, şımartmak",
      vorziehen: "tercih etmek, öne çekmek",
      zurückziehen: "geri çekmek, emekli olmak",
    },
  },

  setzen: {
    meaning: "koymak, oturtmak",
    prefixes: {
      absetzen: "indirmek, çıkarmak, satmak",
      ansetzen: "başlatmak, hazırlamak (yemek)",
      aufsetzen: "yazmak (belge), takmak (şapka)",
      aussetzen: "bırakmak, maruz bırakmak",
      besetzen: "işgal etmek, doldurmak (rol)",
      durchsetzen: "uygulamak, başarmak",
      einsetzen: "kullanmak, yerleştirmek",
      entsetzen: "azletmek, dehşete düşürmek",
      fortsetzen: "devam ettirmek",
      heraussetzen: "riske atmak, bırakmak",
      hinsetzen: "oturtmak, yazmak (aceleyle)",
      nachsetzen: "peşinden gitmek, eklemek",
      übersetzen: "çevirmek, geçirmek (nehir)",
      umsetzen: "uygulamak, dönüştürmek",
      versetzen: "transfer etmek, şaşırtmak",
      voraussetzen: "varsaymak, gerektirmek",
      weitersetzen: "devam ettirmek",
      zusammensetzen: "bir araya getirmek, oluşturmak",
    },
  },

  bringen: {
    meaning: "getirmek",
    prefixes: {
      abbringen: "vazgeçirmek, uzaklaştırmak",
      anbringen: "takmak, yerleştirmek",
      aufbringen: "toplamak (para), sinirlendirmek",
      ausbringen: "dağıtmak, yaymak",
      beibringen: "öğretmek, bildirmek",
      durchbringen: "geçindirmek, başarmak",
      einbringen: "sunmak, kazandırmak",
      entbringen: "kurtulmak, uzaklaşmak",
      erbringen: "sağlamak, yerine getirmek",
      herbringen: "buraya getirmek",
      hinbringen: "oraya götürmek, başarmak",
      mitbringen: "yanında getirmek",
      nachbringen: "sonradan getirmek, tamamlamak",
      überbringen: "teslim etmek, iletmek",
      umbringen: "öldürmek",
      unterbringen: "yerleştirmek, barındırmak",
      verbringen: "geçirmek (zaman)",
      vorbringen: "öne sürmek, ifade etmek",
      weiterbringen: "ilerletmek, geliştirmek",
    },
  },

  denken: {
    meaning: "düşünmek",
    prefixes: {
      andenken: "düşünmek (birine), hatırlamak",
      ausdenken: "tasarlamak, uydurmak",
      bedenken: "düşünmek, tereddüt etmek",
      durchdenken: "iyice düşünmek, planlamak",
      eindenken: "hatırlamak, anımsamak",
      erdenken: "icat etmek, hayal etmek",
      gedenken: "anmak, hatırlamak",
      herausdenken: "bulmak, çözmek",
      hindenken: "düşünmek (bir yere), ima etmek",
      mitdenken: "birlikte düşünmek, hesaba katmak",
      nachdenken: "düşünmek, kafa yormak",
      überdenken: "yeniden düşünmek, gözden geçirmek",
      umdenken: "fikrini değiştirmek, yeniden düşünmek",
      vorausdenken: "önceden düşünmek, tahmin etmek",
      vordenken: "önceden düşünmek, planlamak",
      weiterdenken: "düşünmeye devam etmek",
      zudenken: "düşünmek (birine yönelik), hayal etmek",
    },
  },

  wissen: {
    meaning: "bilmek",
    prefixes: {
      abwissen: "silmek, temizlemek (nadir)",
      anwissen: "bulaştırmak (nadir)",
      auswissen: "iyi bilmek, uzman olmak",
      bewissen: "bilinçli olmak, farkında olmak",
      durchwissen: "tamamen bilmek, hakim olmak",
      einwissen: "bilgilendirmek, öğretmek (nadir)",
      erwissen: "öğrenmek, keşfetmek",
      gewissen: "vicdan azabı çekmek",
      herauswissen: "bulmak, öğrenmek",
      hinwissen: "bilmek (bir yere nasıl gidileceğini)",
      mitwissen: "haberdar olmak, bilmek",
      nachwissen: "kontrol etmek, teyit etmek",
      vorwissen: "önceden bilmek, tahmin etmek",
      weiterwissen: "ne yapacağını bilmek, devam etmek",
      widerwissen: "aleyhinde bilmek, karşı çıkmak (nadir)",
      zuwissen: "birine bildirmek, atfetmek",
    },
  },

  lernen: {
    meaning: "öğrenmek",
    prefixes: {
      ablernen: "öğrenip bırakmak, taklit etmek",
      anlernen: "öğrenmeye başlamak, alışmak",
      auflernen: "ezberlemek, öğrenmek (nadir)",
      auslernen: "bitirip öğrenmek (eğitim), ders çıkarmak",
      belernen: "öğretmek, eğitmek",
      durchlernen: "iyice öğrenmek, çalışarak geçmek",
      einlernen: "öğrenmek, ezberlemek",
      erlernen: "öğrenmek, tecrübe etmek",
      fortlernen: "öğrenmeye devam etmek",
      herauslernen: "keşfetmek, öğrenmek",
      hinlernen: "ek olarak öğrenmek",
      kennenlernen: "tanışmak, tanımak",
      mitlernen: "birlikte öğrenmek",
      nachlernen: "tekrar öğrenmek, taklit etmek",
      umlernen: "yeniden öğrenmek, farklı şekilde öğrenmek",
      verlernen: "öğrenmek, alışmak",
      vorlernen: "önceden öğrenmek, ezberlemek",
      weiterlernen: "öğrenmeye devam etmek",
      zulernen: "öğrenmek (bir şeye yönelik)",
    },
  },

  fahren: {
    meaning: "sürmek, gitmek",
    prefixes: {
      abfahren: "kalkmak (tren, otobüs), ayrılmak",
      anfahren: "başlamak, çarpmak (araçla)",
      auffahren: "çarpmak, açmak (kapı)",
      ausfahren: "dışarı çıkmak, dağıtım yapmak",
      befahren: "kullanmak (yol), geçmek",
      durchfahren: "geçmek, durmadan gitmek",
      einfahren: "içeri girmek, alışmak (makine)",
      entfahren: "ağzından kaçırmak, kaçmak",
      erfahren: "öğrenmek, yaşamak",
      fortfahren: "devam etmek",
      herausfahren: "dışarı çıkmak, patlamak (öfkeyle)",
      herfahren: "buraya gelmek (araçla)",
      hinfahren: "oraya gitmek",
      mitfahren: "birlikte gitmek, eşlik etmek",
      nachfahren: "takip etmek, peşinden gitmek",
      überfahren: "ezmek, geçmek (sınırı)",
      umfahren: "dolaşmak, devirmek",
      verfahren: "yanlış yapmak, işlemek (süreç)",
      vorfahren: "öne geçmek, sürmek (birinin önüne)",
      weiterfahren: "devam etmek (yolculuğ)",
    },
  },
};
export default germanVerbs;
